# Generated by Django 2.0 on 2018-09-20 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20180904_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='message',
            field=models.CharField(default='This is a dummy message only', max_length=4000),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
